#data source
spring:
  datasource:
    url: jdbc:mariadb://database-6.cbph6zdnic3x.ap-northeast-2.rds.amazonaws.com:3306/bridge
    username: admin
    password: kdata4321!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#bucket name for get images from AWS S3 file storage
aws:
  bucket: makesense-s

#baes url
server:
  base:
    url: https://makesense-bridge-production.up.railway.app